name: pet_track
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.1
  google_maps_flutter: ^2.1.1
  flutter_login: ^3.1.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.5
  firebase_core: ^1.11.0
  firebase_database: ^9.0.5
  cloud_firestore: ^3.1.6
  font_awesome_flutter: ^9.2.0
  google_sign_in: ^5.2.3
  flutter_search_bar: ^3.0.0-dev.1
  intl: ^0.17.0
  geolocator: ^8.0.3
  maps_launcher: ^2.0.1
  maps_toolkit: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/map_style.txt